model_path:
  ckpt_path: ./checkpoints/GENIE
  pretrained_Ref_Unet_path: stable-diffusion-v1-5/stable-diffusion-v1-5/
  pretrained_Target_Unet_path: stable-diffusion-v1-5/stable-diffusion-inpainting/
  pretrained_vae_name_or_path: stable-diffusion-v1-5/sd-vae-ft-mse/
  image_encoder_path: image_encoder/
data_path:
  output_dir: ./results/
  test_dir: ./test_images/


  


